version: '3'

services:
    frontend:
        build:
            context: ./client
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - ./client:/app
            - /app/node_modules
